name: Publish @sohcah/openapi-generator

on:
  workflow_dispatch:

concurrency:
  group: publish-openapi-generator
  cancel-in-progress: false

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          cache: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn workspace @sohcah/openapi-generator run build

      - name: Publish to npm
        run: yarn workspace @sohcah/openapi-generator npm publish --provenance
